-- ============================================================
-- MADM - Madrid Digital Music Platform
-- Business-oriented queries
-- ============================================================
-- Run this script after DDL.sql, DML.sql, adminstration.sql
-- and programming.sql, because some queries use views and functions.
USE madm;
-- ============================================================
-- QUERIES
-- ============================================================

-- Query 1: Purchase history for one listener.
-- Need: customer support can review what a listener has bought.
-- Used by: support operator.
SELECT
    u.username,
    o.order_id,
    o.order_date,
    p.name AS product_name,
    pv.name AS variant_name,
    oi.quantity,
    oi.unit_price
FROM `User` u
JOIN `Order` o ON u.account_id = o.account_id
JOIN Order_Item oi ON o.order_id = oi.order_id
JOIN Product_Variant pv ON oi.variant_id = pv.variant_id
JOIN Product p ON pv.product_id = p.product_id
WHERE u.username = 'pepitogrillo'
ORDER BY o.order_date DESC;

-- Query 2: Active premium or family users.
-- Need: check which listeners can use premium features.
-- Used by: platform administrator.
SELECT
    username,
    plan_name,
    start_date,
    end_date
FROM vw_active_subscriptions
WHERE is_premium_user(account_id) = TRUE
ORDER BY username;

-- Query 3: Most popular songs.
-- Need: show songs ranked by plays and stars.
-- Used by: listeners and editorial team.
SELECT
    title,
    genre,
    total_plays,
    total_stars
FROM vw_song_popularity
ORDER BY total_plays DESC, total_stars DESC;

-- Query 4: Revenue generated by each artist.
-- Need: evaluate store performance per artist.
-- Used by: artists and business administrators.
SELECT
    artist_name,
    units_sold,
    gross_revenue
FROM vw_artist_sales_summary
ORDER BY gross_revenue DESC;

-- Query 5: Low stock product variants.
-- Need: know which products should be restocked soon.
-- Used by: artist store operator.
SELECT
    artist_name,
    product_name,
    variant_name,
    stock
FROM vw_low_stock_products
ORDER BY stock ASC;

-- Query 6: Pending artist verification requests.
-- Need: moderation team can review artists waiting for approval.
-- Used by: MADM administrator.
SELECT
    ar.request_id,
    a.name AS artist_name,
    ar.submission_date,
    ar.notes
FROM ArtistRequest ar
JOIN Artist a ON ar.account_id = a.account_id
WHERE ar.status = 'pending'
ORDER BY ar.submission_date ASC;

-- Query 7: Playlists created by premium users.
-- Need: list valid playlists and their owners.
-- Used by: product team.
SELECT
    p.playlist_id,
    p.name AS playlist_name,
    u.username AS owner
FROM Playlist p
JOIN `User` u ON p.account_id = u.account_id
WHERE is_premium_user(u.account_id) = TRUE
ORDER BY p.name;

-- Query 8: Number of songs in each playlist.
-- Need: measure playlist size and activity.
-- Used by: product team.
SELECT
    p.name AS playlist_name,
    COUNT(ps.song_id) AS songs_count
FROM Playlist p
LEFT JOIN Playlist_Song ps ON p.playlist_id = ps.playlist_id
GROUP BY p.playlist_id, p.name
ORDER BY songs_count DESC;

-- Query 9: Listening history for one user.
-- Need: show recently played songs by a listener.
-- Used by: listener profile page.
SELECT
    u.username,
    pl.played_at,
    s.title AS song_title
FROM Play pl
JOIN `User` u ON pl.account_id = u.account_id
JOIN Song s ON pl.song_id = s.song_id
WHERE u.username = 'josefa03'
ORDER BY pl.played_at DESC;

-- Query 10: Plays by genre.
-- Need: know which genres are listened to the most.
-- Used by: catalog manager.
SELECT
    genre,
    SUM(total_plays) AS genre_plays
FROM vw_song_popularity
GROUP BY genre
ORDER BY genre_plays DESC;

-- Query 11: Songs with more plays than the average.
-- Need: identify songs performing above the catalog average.
-- Used by: recommendation system.
SELECT
    title,
    genre,
    total_plays
FROM vw_song_popularity
WHERE total_plays > (
    SELECT AVG(total_plays)
    FROM vw_song_popularity
)
ORDER BY total_plays DESC;

-- Query 12: Followers per artist.
-- Need: compare artist audience size.
-- Used by: artist relations team.
SELECT
    a.name AS artist_name,
    COUNT(fa.account_id) AS followers_count
FROM Artist a
LEFT JOIN Follow_Artist fa ON a.account_id = fa.artist_id
GROUP BY a.account_id, a.name
ORDER BY followers_count DESC;

-- Query 13: Albums saved in user collections.
-- Need: know which releases are being saved by listeners.
-- Used by: artists and administrators.
SELECT
    al.title AS album_title,
    a.name AS artist_name,
    COUNT(c.account_id) AS saved_by_users
FROM Album al
JOIN Artist a ON al.account_id = a.account_id
LEFT JOIN Collection c ON al.album_id = c.album_id
GROUP BY al.album_id, al.title, a.name
ORDER BY saved_by_users DESC;

-- Query 14: Monthly subscription income.
-- Need: monitor recurring revenue generated by subscription plans.
-- Used by: business administrator.
SELECT
    DATE_FORMAT(s.start_date, '%Y-%m') AS month,
    COUNT(s.subscription_id) AS subscriptions_started,
    SUM(pl.price) AS subscription_income
FROM Subscription s
JOIN Plan pl ON s.plan_id = pl.plan_id
WHERE s.status = 'active'
GROUP BY DATE_FORMAT(s.start_date, '%Y-%m')
ORDER BY month;

-- Query 15: Collaborations between artists.
-- Need: identify songs involving more than one artist.
-- Used by: editorial team.
SELECT
    s.title AS song_title,
    COUNT(sa.account_id) AS artist_count
FROM Song s
JOIN Song_Artist sa ON s.song_id = sa.song_id
GROUP BY s.song_id, s.title
HAVING COUNT(sa.account_id) > 1;
